/**
 * Unified data layer.
 *
 * When VITE_SUPABASE_URL + VITE_SUPABASE_ANON_KEY are set, every hook and
 * mutation hits the real Supabase tables.  Otherwise the in-memory mock store
 * is used so the app works without any backend credentials.
 *
 * All exported hooks expose the same shape as mockStore so pages import from
 * here and never need to branch themselves.
 */
import { useEffect, useMemo, useRef, useState, useCallback } from "react";
import { useQuery } from "@tanstack/react-query";
import { supabase, HAS_REAL_SUPABASE } from "./supabase";
import { getCredenceHeaders } from "./credenceHeaders";
import { isDemoMode } from "@/store/graphStore";
import { DEMO_PROSPECTS } from "./demoData";
import {
  store,
  useProspects as mockProspects,
  useProspect as mockProspect,
  useSignalsFor as mockSignalsFor,
  useLatestScore as mockLatestScore,
  useLatestRun as mockLatestRun,
  useWeights as mockWeights,
  useScoresFor as mockScoresFor,
} from "./mockStore";
import type { Prospect, Signal, Score, SignalWeight, ScoringRun } from "./mockStore";
import type { PersonConnectionRecord } from "./graph";
export type { Prospect, Signal, Score, SignalWeight, ScoringRun } from "./mockStore";
export type { PersonConnectionRecord } from "./graph";

// ─── Type normalizers ────────────────────────────────────────────────────────
// Supabase rows use `id` (UUID string) and ISO timestamps.
// The mock store (and pages) use `_id` and millisecond timestamps.
type SupaRow = Record<string, unknown> & { id: string };
type SupaProspectRow = SupaRow & {
  created_at: string | number;
  updated_at: string | number;
};
type SupaSignalRow = SupaRow & {
  prospect_id: string;
  collected_at: string | number;
};
type SupaScoreRow = SupaRow & {
  prospect_id: string;
  computed_at: string | number;
  model_version?: string;
};
type SupaRunRow = SupaRow & {
  started_at: string | number;
  completed_at?: string | number | null;
};

const toP = (r: SupaProspectRow) => ({
  ...r,
  _id: r.id,
  created_at: +new Date(r.created_at),
  updated_at: +new Date(r.updated_at),
});
const toSig = (r: SupaSignalRow) => ({
  ...r,
  _id: r.id,
  collected_at: +new Date(r.collected_at),
});
const toScore = (r: SupaScoreRow) => ({
  ...r,
  _id: r.id,
  computed_at: +new Date(r.computed_at),
});
const toWeight = (r: SupaRow) => ({ ...r, _id: r.id });
const toRun = (r: SupaRunRow) => ({
  ...r,
  _id: r.id,
  started_at: +new Date(r.started_at),
  completed_at: r.completed_at ? +new Date(r.completed_at) : undefined,
});

// Stable empty references so consumers using `useMemo`/`useEffect` deps don't
// re-trigger when react-query is still loading.
const EMPTY_ARRAY: unknown[] = Object.freeze([]) as unknown[];
const EMPTY_RECORD: Record<string, unknown> = Object.freeze({}) as Record<string, unknown>;

// ─── Snapshot mode ────────────────────────────────────────────────────────────
// When VITE_USE_SNAPSHOT=true, every bulk read resolves from a one-shot JSON
// snapshot of the Supabase tables (src/lib/snapshot.json) instead of hitting
// PostgREST at runtime. Generated by scripts/snapshot-supabase.mjs. Demo-only:
// scoring writes still go through Supabase but won't be visible until you
// re-run the snapshot script.
const USE_SNAPSHOT =
  HAS_REAL_SUPABASE && (import.meta.env.VITE_USE_SNAPSHOT as string | undefined) === "true";

interface SnapshotShape {
  prospects: SupaProspectRow[];
  scores: SupaScoreRow[];
  signals: SupaSignalRow[];
  signal_weights: SupaRow[];
}

let snapshotPromise: Promise<SnapshotShape> | null = null;
function loadSnapshot(): Promise<SnapshotShape> {
  // Vite handles JSON imports natively; dynamic import lets us keep the
  // ~50MB blob out of the landing-page chunk and only pay the parse cost
  // when the user actually navigates to a route that needs it.
  if (!snapshotPromise) {
    snapshotPromise = import("./snapshot.json").then((m) => m.default as SnapshotShape);
  }
  return snapshotPromise;
}

// ─── Supabase hooks ───────────────────────────────────────────────────────────

// Supabase's REST endpoint defaults to a max of 1000 rows per request. Page
// through the result set so callers get every row regardless of table size.
const PAGE = 1000;
// `build` returns a Supabase query builder. We do not pin the chainable
// type because @supabase/supabase-js doesn't export it publicly and pinning
// would couple us to internals that change between releases.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
async function fetchAllRows<T = SupaRow>(build: () => any): Promise<T[]> {
  const all: T[] = [];
  for (let from = 0; ; from += PAGE) {
    const { data, error } = await build().range(from, from + PAGE - 1);
    if (error) {
      console.error("[db] fetchAllRows error:", error);
      return all;
    }
    if (!data || data.length === 0) break;
    all.push(...(data as T[]));
    if (data.length < PAGE) break;
  }
  return all;
}

// All bulk Supabase queries share these defaults so multiple consumers of the
// same data hit a single in-memory cache instead of refetching independently.
// staleTime: pages won't refetch on remount within 5 min — kills the
// fan-out where /, /discover, /settings each paginated `prospects`/`scores`
// 11–21 times per load.
const BULK_STALE_MS = 5 * 60 * 1000;

function useSupaProspects() {
  const { data } = useQuery({
    queryKey: ["prospects", USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT) {
        const snap = await loadSnapshot();
        return snap.prospects.map(toP);
      }
      const rows = await fetchAllRows<SupaProspectRow>(() =>
        supabase!
          .from("prospects")
          .select("*")
          .order("created_at", { ascending: false })
          .order("id", { ascending: true }),
      );
      // Dedup by id: offset-pagination can return a boundary row on both
      // page N and N+1 when many rows share the same created_at.
      const seen = new Set<string>();
      const unique: SupaProspectRow[] = [];
      for (const r of rows) {
        if (seen.has(r.id)) continue;
        seen.add(r.id);
        unique.push(r);
      }
      return unique.map(toP);
    },
  });
  return data ?? EMPTY_ARRAY;
}

function useSupaProspect(id?: string) {
  const { data } = useQuery({
    queryKey: ["prospect", id, USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE && !!id,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT) {
        const snap = await loadSnapshot();
        const row = snap.prospects.find((p) => p.id === id);
        return row ? toP(row) : null;
      }
      const { data: row } = await supabase!
        .from("prospects")
        .select("*")
        .eq("id", id!)
        .single();
      return row ? toP(row) : null;
    },
  });
  return data ?? null;
}

// Per-prospect signals — always hits live Supabase, even in snapshot mode.
// The bulk snapshot strips signals.value / raw_data (40MB JSONB blobs) for
// graph-build perf, so the inspector panel needs the live row to render
// evidence values. Single small fetch (~50KB) per inspector open.
function useSupaSignalsFor(id?: string) {
  const { data } = useQuery({
    queryKey: ["signals", id],
    enabled: HAS_REAL_SUPABASE && !!id,
    staleTime: BULK_STALE_MS,
    queryFn: async () => {
      const { data: rows } = await supabase!
        .from("signals")
        .select("*")
        .eq("prospect_id", id!);
      return rows ? rows.map(toSig) : [];
    },
  });
  return data ?? EMPTY_ARRAY;
}

// Shared full-table fetch — every `useSupaSignalsForMany(ids)` consumer reads
// from this single cached result and just re-derives the per-id grouping
// in memory. Previously each consumer paginated the entire signals table.
function useAllSignalsCached() {
  const { data } = useQuery({
    queryKey: ["signals", "all", USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT) {
        const snap = await loadSnapshot();
        return snap.signals;
      }
      return fetchAllRows<SupaSignalRow>(() =>
        supabase!
          .from("signals")
          .select("*")
          .order("collected_at", { ascending: false }),
      );
    },
  });
  return data ?? EMPTY_ARRAY;
}

function useSupaSignalsForMany(ids: string[]) {
  const rows = useAllSignalsCached() as SupaSignalRow[];
  return useMemo(() => {
    if (!ids.length) return EMPTY_RECORD;
    const wanted = new Set(ids);
    const out: Record<string, ReturnType<typeof toSig>[]> = {};
    for (const r of rows) {
      if (!wanted.has(r.prospect_id)) continue;
      (out[r.prospect_id] ??= []).push(toSig(r));
    }
    return out;
  }, [ids, rows]);
}

// Mock fallback: group whatever the in-memory store has by prospect_id.
// Named `use…` so React's hook rules don't fire — this *is* a hook.
function useMockSignalsForMany(ids: string[]) {
  const [data, setData] = useState<Record<string, unknown[]>>({});
  const key = ids.length ? `${ids.length}` : "";
  useEffect(() => {
    if (!ids.length) return;
    const out: Record<string, unknown[]> = {};
    for (const id of ids) out[id] = store.signals.filter((s) => s.prospect_id === id);
    setData(out);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [key]);
  return data;
}

// Preference order when multiple scorer variants have written rows for the
// same prospect. Higher tier wins regardless of `computed_at`.
const MODEL_PRECEDENCE: Record<string, number> = {
  chartreuse_llm_v1: 1,
  chartreuse_deterministic_v1: 2,
  lightweight_v1: 3,
};
const pickBestScoreRow = <T extends { model_version?: string; computed_at: string | number }>(
  rows: T[],
): T | null => {
  if (!rows?.length) return null;
  const sorted = [...rows].sort((a, b) => {
    const ta = MODEL_PRECEDENCE[a.model_version ?? ""] ?? 9;
    const tb = MODEL_PRECEDENCE[b.model_version ?? ""] ?? 9;
    if (ta !== tb) return ta - tb;
    // same tier → newest first
    return +new Date(b.computed_at) - +new Date(a.computed_at);
  });
  return sorted[0];
};

function useSupaLatestScore(id?: string) {
  const [data, setData] = useState<ReturnType<typeof toScore> | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const fetch = useCallback(async () => {
    if (!id) return false;
    if (USE_SNAPSHOT) {
      // Snapshot mode: scores were already best-picked at snapshot time, so a
      // single lookup is enough — no polling needed (scoring writes won't be
      // visible until the snapshot script re-runs anyway).
      const snap = await loadSnapshot();
      const row = snap.scores.find((s) => s.prospect_id === id);
      if (row) {
        setData(toScore(row));
        return true;
      }
      return false;
    }
    // Pull every score row for this prospect; the in-memory ranker gives us
    // LLM > deterministic > lightweight precedence without a second query.
    const { data: rows } = await supabase!
      .from("scores")
      .select("*")
      .eq("prospect_id", id)
      .order("computed_at", { ascending: false });
    const best = pickBestScoreRow(rows ?? []);
    if (best) {
      setData(toScore(best));
      return true;
    }
    return false;
  }, [id]);

  useEffect(() => {
    if (!id) return;
    let active = true;
    fetch().then((found) => {
      if (!found && active && !USE_SNAPSHOT) {
        // Poll until the scoring run writes a score (up to 90 s)
        let attempts = 0;
        timerRef.current = setInterval(async () => {
          attempts++;
          const ok = await fetch();
          if (ok || attempts >= 90) clearInterval(timerRef.current!);
        }, 1000);
      }
    });
    return () => {
      active = false;
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [id, fetch]);

  return data;
}

function useSupaLatestRun(id?: string) {
  const [data, setData] = useState<ReturnType<typeof toRun> | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  const fetch = useCallback(async () => {
    if (!id) return null;
    // Snapshot mode never has a "running" scoring_runs row to poll —
    // the offline JSON is static. Skip the round trip entirely.
    if (USE_SNAPSHOT) return null;
    const { data: rows } = await supabase!
      .from("scoring_runs")
      .select("*")
      .eq("prospect_id", id)
      .order("started_at", { ascending: false })
      .limit(1);
    if (rows?.length) {
      setData(toRun(rows[0]));
      return rows[0];
    }
    return null;
  }, [id]);

  useEffect(() => {
    if (!id || USE_SNAPSHOT) return;
    fetch().then((run) => {
      if (run && (run.status === "running" || run.status === "pending")) {
        timerRef.current = setInterval(async () => {
          const r = await fetch();
          if (r?.status === "complete" || r?.status === "error") {
            clearInterval(timerRef.current!);
          }
        }, 500);
      }
    });
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [id, fetch]);

  return data;
}

function useSupaWeights() {
  const { data } = useQuery({
    queryKey: ["weights", USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT) {
        const snap = await loadSnapshot();
        return snap.signal_weights.map(toWeight);
      }
      const { data: rows } = await supabase!.from("signal_weights").select("*");
      return rows ? rows.map(toWeight) : [];
    },
  });
  return data ?? EMPTY_ARRAY;
}

// Shared full-table scores cache. Same pattern as useAllSignalsCached.
function useAllScoresCached() {
  const { data } = useQuery({
    queryKey: ["scores", "all", USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT) {
        const snap = await loadSnapshot();
        return snap.scores;
      }
      return fetchAllRows<SupaScoreRow>(() =>
        supabase!
          .from("scores")
          .select("*")
          .order("computed_at", { ascending: false }),
      );
    },
  });
  return data ?? EMPTY_ARRAY;
}

function useSupaScoresFor(ids: string[]) {
  const rows = useAllScoresCached() as SupaScoreRow[];
  return useMemo(() => {
    if (!ids.length) return EMPTY_RECORD;
    const wanted = new Set(ids);
    const grouped: Record<string, SupaScoreRow[]> = {};
    for (const r of rows) {
      if (!wanted.has(r.prospect_id)) continue;
      (grouped[r.prospect_id] ??= []).push(r);
    }
    const out: Record<string, ReturnType<typeof toScore>> = {};
    for (const [pid, list] of Object.entries(grouped)) {
      const best = pickBestScoreRow(list);
      if (best) out[pid] = toScore(best);
    }
    return out;
  }, [ids, rows]);
}

// ─── Supabase mutations ───────────────────────────────────────────────────────

const ALL_SOURCES = [
  "linkedin_profile",
  "linkedin_posts",
  "uspto",
  "github",
  "conference",
  "company_hiring",
  "crunchbase",
  "mutual_connections",
] as const;

const SOURCE_TO_SIGNALS: Record<string, string[]> = {
  linkedin_profile: ["tenure_years", "recommendations"],
  linkedin_posts: ["post_activity"],
  uspto: ["patent_count", "patent_citations"],
  github: ["github_commits"],
  conference: ["conference_talks"],
  company_hiring: ["hiring_signal"],
  crunchbase: ["crunchbase_role"],
  mutual_connections: ["mutual_connections"],
};

const rand = (min: number, max: number) =>
  Math.floor(Math.random() * (max - min + 1)) + min;
const norm = (n: number) => Math.max(0, Math.min(100, 100 * (1 - Math.exp(-n / 15))));

// Intentionally empty — we don't emit generic falsification boilerplate per
// user directive. Any falsification note must be derived from THIS prospect's
// actual coverage/confidence state, emitted inline where it is computed.
const FALSIFICATION_NOTES: string[] = [];

async function supaCreateProspect(p: {
  name: string;
  company: string;
  role: string;
  roles?: string[];
  keywords?: string[];
  industry: string;
  linkedin_url?: string;
}) {
  const { data, error } = await supabase!
    .from("prospects")
    .insert(p)
    .select()
    .single();
  if (error) throw error;
  return data.id as string;
}

const API_BASE: string =
  (import.meta.env.VITE_API_URL as string | undefined)?.replace(/\/+$/, "") ||
  "http://localhost:8000";

/**
 * Score a prospect by:
 *   1. Creating a `scoring_runs` row so the /validate UX can poll progress.
 *   2. Trying our FastAPI `/validate` endpoint first. On success, map the
 *      ScoreResult to a `public.scores` row.
 *   3. On 404 / network error, falling back to the lightweight signal-based
 *      scorer (seeds mock signals for new prospects, then weighted sigmoid).
 *   4. Marking `scoring_runs` complete when done.
 *
 * Replaces the prior `supabase.functions.invoke("validate-agent")` which
 * referenced an edge function that was never deployed.
 */
async function supaRunScoring(prospect_id: string): Promise<void> {
  // 1. scoring_runs row — frontend polling UX reads this.
  const run = {
    prospect_id,
    status: "running" as const,
    sources_attempted: [...ALL_SOURCES],
    sources_succeeded: [] as string[],
    current_source: null,
  };
  const { data: runRow } = await supabase!
    .from("scoring_runs")
    .insert(run)
    .select()
    .single();
  const runId = runRow?.id as string | undefined;

  const finish = async (status: "complete" | "error", extra?: Record<string, unknown>) => {
    if (!runId) return;
    await supabase!
      .from("scoring_runs")
      .update({ status, completed_at: new Date().toISOString(), ...(extra ?? {}) })
      .eq("id", runId);
  };

  try {
    // 2. Fetch prospect to get name/industry/role for our /validate call.
    const { data: prospect, error: fetchErr } = await supabase!
      .from("prospects")
      .select("name, company, role, industry")
      .eq("id", prospect_id)
      .single();
    if (fetchErr || !prospect) {
      console.error("[supaRunScoring] fetch prospect failed:", fetchErr);
      await finish("error", { error_log: "prospect not found" });
      return;
    }

    // 3. Try FastAPI /validate. Returns a rich ScoreResult when the person
    //    matches a lead_scoring.people row (ILIKE on name + industry).
    let used_fastapi = false;
    try {
      const resp = await fetch(`${API_BASE}/validate`, {
        method: "POST",
        // `getCredenceHeaders()` attaches `X-Credence-Demo: true` in demo mode
        // (Wave 6 M5) and will attach `Authorization: Bearer <jwt>` once M3
        // wires authenticated live mode.
        headers: { "Content-Type": "application/json", ...getCredenceHeaders() },
        body: JSON.stringify({
          name: prospect.name,
          industry: prospect.industry,
          role: prospect.role,
        }),
      });
      if (resp.ok) {
        const result = (await resp.json()) as {
          composite: number;
          role_fit: number;
          authority_fit: number;
          company_fit: number;
          confidence: number;
          reasoning?: string;
        };
        // Map to frontend schema: authenticity = meta-trust (our confidence),
        // authority = authority_fit, warmth = role_fit, overall = composite.
        await supabase!.from("scores").insert({
          prospect_id,
          authenticity_score: result.confidence,
          authority_score: result.authority_fit,
          warmth_score: result.role_fit,
          overall_score: result.composite,
          falsification_notes: result.reasoning
            ? [`reasoning: ${String(result.reasoning).slice(0, 240)}`]
            : [],
        });
        used_fastapi = true;
      } else if (resp.status !== 404) {
        console.error("[supaRunScoring] /validate unexpected status:", resp.status);
      }
    } catch (err) {
      console.error("[supaRunScoring] /validate fetch error:", err);
    }

    // 4. Fallback — seed mock signals + lightweight weighted-sigmoid scorer.
    if (!used_fastapi) {
      const { data: existing } = await supabase!
        .from("signals")
        .select("id")
        .eq("prospect_id", prospect_id)
        .limit(1);
      if (!existing?.length) {
        const rows: Record<string, unknown>[] = [];
        for (const source of ALL_SOURCES) {
          for (const signal_type of SOURCE_TO_SIGNALS[source]) {
            // value is scalar — `supaComputeScores` does `Number(s.value)` so
            // passing an object here would NaN-coalesce to 0.
            rows.push({
              prospect_id,
              source,
              signal_type,
              value: rand(5, 30),
              raw_data: { _synthetic: true, via: "supaRunScoring-fallback" },
              weight: 1,
              confidence: +(0.6 + Math.random() * 0.35).toFixed(2),
            });
          }
        }
        if (rows.length > 0) {
          await supabase!.from("signals").insert(rows);
        }
      }
      await supaComputeScores([prospect_id]);
    }

    await finish("complete", { sources_succeeded: [...ALL_SOURCES] });
  } catch (err) {
    console.error("[supaRunScoring] fatal:", err);
    await finish("error", { error_log: String(err).slice(0, 500) });
  }
}

async function supaUpsertWeight(
  signal_type: string,
  a: number,
  au: number,
  w: number
) {
  await supabase!.from("signal_weights").upsert(
    { signal_type, authenticity_weight: a, authority_weight: au, warmth_weight: w },
    { onConflict: "signal_type" }
  );
}

// Signals land in `public.signals.value` as either a scalar (number/string) or
// a JSON object. Historically the bulk-import pipeline wraps scalars as
// `{raw: N}` (and sometimes richer blobs like `{about, method, headline}`).
// `Number({...}) || 0` collapsed every object to 0 and produced 0/0/0/0 scores.
// Normalize defensively here so one scorer handles both shapes.
function extractSignalValue(v: unknown): number {
  if (typeof v === "number") return isFinite(v) ? v : 0;
  if (typeof v === "string") { const n = Number(v); return isFinite(n) ? n : 0; }
  if (v && typeof v === "object") {
    const obj = v as Record<string, unknown>;
    if ("raw" in obj) return extractSignalValue(obj.raw);
    if ("value" in obj) return extractSignalValue(obj.value);
  }
  return 0;
}

interface WeightRow {
  signal_type: string;
  authenticity_weight: number;
  authority_weight: number;
  warmth_weight: number;
}
async function supaComputeScores(prospectIds: string[]) {
  const { data: weights } = await supabase!.from("signal_weights").select("*");
  const wmap = new Map(
    ((weights ?? []) as WeightRow[]).map((w) => [
      w.signal_type,
      { a: w.authenticity_weight, au: w.authority_weight, w: w.warmth_weight },
    ])
  );
  for (const pid of prospectIds) {
    const { data: signals } = await supabase!
      .from("signals")
      .select("*")
      .eq("prospect_id", pid);
    if (!signals?.length) continue;
    let aN = 0, aD = 0, auN = 0, auD = 0, wN = 0, wD = 0;
    for (const s of signals) {
      const w = wmap.get(s.signal_type);
      if (!w) continue;
      const v = norm(extractSignalValue(s.value));
      const base = (s.weight ?? 1) * (s.confidence ?? 1);
      aN += v * base * w.a; aD += base * w.a;
      auN += v * base * w.au; auD += base * w.au;
      wN += v * base * w.w; wD += base * w.w;
    }
    const round = (n: number) => Math.round(n * 10) / 10;
    await supabase!.from("scores").insert({
      prospect_id: pid,
      authenticity_score: round(aD ? aN / aD : 0),
      authority_score: round(auD ? auN / auD : 0),
      warmth_score: round(wD ? wN / wD : 0),
      overall_score: round(
        0.4 * (aD ? aN / aD : 0) +
        0.4 * (auD ? auN / auD : 0) +
        0.2 * (wD ? wN / wD : 0)
      ),
      falsification_notes: FALSIFICATION_NOTES,
    });
  }
}

// ─── Exported unified hooks ───────────────────────────────────────────────────
//
// Three-way dispatch on demo / real-Supabase / mock:
//   1. `?demo=true` → return canned data from `demoData.ts` (no network)
//   2. real Supabase env configured → hit the live REST API
//   3. otherwise → in-memory mock store
//
// The demo-mode short-circuit (per CONTRACTS.md Contract 5: "Demo mode
// performs zero Supabase queries") must be checked BEFORE the
// `HAS_REAL_SUPABASE` flag, because Supabase env vars are typically
// configured in real deploys even when a viewer flips `?demo=true`.

// Demo-mode stand-ins. Hooks must remain callable (React rules-of-hooks
// don't allow conditional invocation), so we wrap the constants in
// minimal hooks that always run but return stable references.
const useDemoProspects = (): Prospect[] => useMemo(() => [...DEMO_PROSPECTS], []);
const useDemoProspect = (id: string | null | undefined): Prospect | undefined => {
  return useMemo(
    () => (id ? DEMO_PROSPECTS.find((p) => p._id === id) : undefined),
    [id],
  );
};
const _emptySignalArray: Signal[] = [];
const _emptySignalsByProspect: Record<string, Signal[]> = {};
const _emptyScoresByProspect: Record<string, Score> = {};
const _emptyWeightsArray: SignalWeight[] = [];
const _emptyConnectionsByProspect: Record<string, PersonConnectionRecord[]> = {};
const useDemoSignalsFor = (_prospectId: string | null | undefined): Signal[] => _emptySignalArray;
const useDemoSignalsForMany = (_ids: string[]): Record<string, Signal[]> => _emptySignalsByProspect;
const useDemoLatestScore = (_prospectId: string | null | undefined): Score | undefined => undefined;
const useDemoLatestRun = (_prospectId: string | null | undefined): ScoringRun | undefined => undefined;
const useDemoWeights = (): SignalWeight[] => _emptyWeightsArray;
const useDemoScoresFor = (_ids: string[]): Record<string, Score> => _emptyScoresByProspect;
const useDemoPersonConnections = (
  _ids: string[],
): Record<string, PersonConnectionRecord[]> => _emptyConnectionsByProspect;
const useMockPersonConnections = (
  _ids: string[],
): Record<string, PersonConnectionRecord[]> => _emptyConnectionsByProspect;
// Supabase row shape: person_connections embedded with both endpoints'
// persons rows (PostgREST FK-embed pattern). The `!person_a_id` /
// `!person_b_id` disambiguators tell PostgREST which FK to follow — both
// FKs target persons, so the alias is required.
type SupaPersonConnectionRow = {
  id: string;
  person_a_id: string;
  person_b_id: string;
  connection_type: string;
  computed_strength: number;
  base_strength: number;
  recency_factor: number;
  frequency_factor: number;
  corroboration_factor: number;
  last_active_year: number | null;
  corroboration_count: number;
  source_type_count: number;
  evidence_ids: string[];
  person_a: { source_prospect_id: string | null } | null;
  person_b: { source_prospect_id: string | null } | null;
};

// Single full-table fetch + cache. Mirror useAllSignalsCached / useAllScoresCached.
// Once SwiftElk's career_overlap_clustering ramps to all 51k+ pairs, this
// table grows but stays bounded — current size 523, expected steady-state
// 5-30k. PAGE-size pagination handles it cleanly.
function useAllPersonConnectionsCached() {
  const { data } = useQuery({
    queryKey: ["person_connections", "all", USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT) return [] as SupaPersonConnectionRow[];
      return fetchAllRows<SupaPersonConnectionRow>(() =>
        supabase!
          .from("person_connections")
          .select(
            "*,person_a:persons!person_a_id(source_prospect_id),person_b:persons!person_b_id(source_prospect_id)",
          )
          .order("computed_strength", { ascending: false }),
      );
    },
  });
  return data ?? EMPTY_ARRAY;
}

// Companion: full table of connection_evidence (~5-30k expected steady-
// state, ~3k current). Indexed by id so the per-prospect-connection
// merge below can pull rich payload (company_name, overlap years, etc.)
// keyed off person_connections.evidence_ids[0]. Without this join, the
// sixth pass renders edges with synthesized strength fields only, and
// warmPaths.ts's templates fall back to generic "shared tenure" text.
type SupaConnectionEvidenceRow = {
  id: string;
  source_type: string;
  // SwiftElk's career_overlap_clustering currently writes structured_value
  // double-encoded (jsonb-typed string containing JSON object) — see msg
  // 191 follow-up. Tolerate both shapes here so the FE doesn't depend on
  // a server-side fix landing first.
  structured_value: Record<string, unknown> | string | null;
};
function useAllConnectionEvidenceCached() {
  const { data } = useQuery({
    queryKey: ["connection_evidence", "all", USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT) return [] as SupaConnectionEvidenceRow[];
      return fetchAllRows<SupaConnectionEvidenceRow>(() =>
        supabase!
          .from("connection_evidence")
          .select("id,source_type,structured_value"),
      );
    },
  });
  return data ?? EMPTY_ARRAY;
}

// SwiftElk's W9 read-cache (msg 204): denormalized top-K-per-prospect view
// with partner display fields + pre-merged evidence. Read path is now a
// single bounded query keyed on visible prospect_ids — no full-table scan
// of person_connections, no JS-side persons-JOIN. ~10,000× faster
// (43-page paginated → 2.2ms top-K fetch).
type SupaProspectWarmPathRow = {
  prospect_id: string;
  rank: number;
  partner_prospect_id: string;
  connection_type: string;
  computed_strength: number;
  evidence: Record<string, unknown> | string | null;
  partner_name: string | null;
  partner_company: string | null;
  partner_title: string | null;
};

function useSupaPersonConnections(
  ids: string[],
): Record<string, PersonConnectionRecord[]> {
  const idsKey = ids.join(",");
  const { data } = useQuery({
    queryKey: ["prospect_warm_paths", idsKey, USE_SNAPSHOT ? "snapshot" : "live"],
    enabled: HAS_REAL_SUPABASE && ids.length > 0,
    staleTime: USE_SNAPSHOT ? Infinity : BULK_STALE_MS,
    queryFn: async () => {
      if (USE_SNAPSHOT || !ids.length) return [] as SupaProspectWarmPathRow[];
      // PostgREST .in() caps URL length at ~7-8k chars. UUIDs are 36 chars
      // each + comma, so ~200 ids per request. Chunk if needed.
      const CHUNK = 200;
      const out: SupaProspectWarmPathRow[] = [];
      for (let i = 0; i < ids.length; i += CHUNK) {
        const chunk = ids.slice(i, i + CHUNK);
        const { data, error } = await supabase!
          .from("prospect_warm_paths")
          .select(
            "prospect_id,rank,partner_prospect_id,connection_type,computed_strength,evidence,partner_name,partner_company,partner_title",
          )
          .in("prospect_id", chunk)
          .order("rank", { ascending: true });
        if (error) {
          console.error("[db] prospect_warm_paths fetch error:", error);
          continue;
        }
        if (data) out.push(...(data as SupaProspectWarmPathRow[]));
      }
      return out;
    },
  });

  return useMemo(() => {
    const rows = (data ?? []) as SupaProspectWarmPathRow[];
    if (!ids.length || !rows.length) return _emptyConnectionsByProspect;
    const out: Record<string, PersonConnectionRecord[]> = {};
    for (const r of rows) {
      // evidence may be a parsed object, a JSON-stringified blob (legacy
      // double-encode), or null. Tolerate all.
      let sv: Record<string, unknown> = {};
      const raw = r.evidence;
      if (raw && typeof raw === "object" && !Array.isArray(raw)) {
        sv = { ...raw };
      } else if (typeof raw === "string" && raw.length > 0) {
        try {
          const parsed = JSON.parse(raw);
          if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
            sv = parsed as Record<string, unknown>;
          }
        } catch {
          // ignore
        }
      }
      // Bridge server-side keys to evidenceFromSignal's expected shape.
      if (sv.overlap_start !== undefined && sv.overlap_start_year === undefined) {
        sv.overlap_start_year = sv.overlap_start;
      }
      if (sv.overlap_end !== undefined && sv.overlap_end_year === undefined) {
        sv.overlap_end_year = sv.overlap_end;
      }
      const rec: PersonConnectionRecord = {
        connected_prospect_id: r.partner_prospect_id,
        connection_type: r.connection_type,
        computed_strength: Number(r.computed_strength) || 0,
        structured_value: sv,
      };
      (out[r.prospect_id] ??= []).push(rec);
    }
    return out;
  }, [ids, data]);
}

const _DEMO = isDemoMode();

export const useProspects = _DEMO
  ? useDemoProspects
  : (HAS_REAL_SUPABASE ? useSupaProspects : mockProspects);
export const useProspect = _DEMO
  ? useDemoProspect
  : (HAS_REAL_SUPABASE ? useSupaProspect : mockProspect);
export const useSignalsFor = _DEMO
  ? useDemoSignalsFor
  : (HAS_REAL_SUPABASE ? useSupaSignalsFor : mockSignalsFor);
export const useSignalsForMany = _DEMO
  ? useDemoSignalsForMany
  : (HAS_REAL_SUPABASE ? useSupaSignalsForMany : useMockSignalsForMany);
// Signal-value normalizer exposed for the Discover row-enrichment UX.
export { extractSignalValue };
export const useLatestScore = _DEMO
  ? useDemoLatestScore
  : (HAS_REAL_SUPABASE ? useSupaLatestScore : mockLatestScore);
export const useLatestRun = _DEMO
  ? useDemoLatestRun
  : (HAS_REAL_SUPABASE ? useSupaLatestRun : mockLatestRun);
export const useWeights = _DEMO
  ? useDemoWeights
  : (HAS_REAL_SUPABASE ? useSupaWeights : mockWeights);
export const useScoresFor = _DEMO
  ? useDemoScoresFor
  : (HAS_REAL_SUPABASE ? useSupaScoresFor : mockScoresFor);
export const usePersonConnections = _DEMO
  ? useDemoPersonConnections
  : (HAS_REAL_SUPABASE ? useSupaPersonConnections : useMockPersonConnections);

// ─── Exported unified mutations ───────────────────────────────────────────────

export const db = HAS_REAL_SUPABASE
  ? {
      createProspect: supaCreateProspect,
      runScoring: supaRunScoring,
      upsertWeight: supaUpsertWeight,
      computeScores: supaComputeScores,
    }
  : {
      createProspect: (p: Parameters<typeof store.createProspect>[0]) =>
        Promise.resolve(store.createProspect(p)),
      runScoring: (id: string) => store.runScoring(id),
      upsertWeight: (st: string, a: number, au: number, w: number) => {
        store.upsertWeight(st, a, au, w);
        return Promise.resolve();
      },
      computeScores: (ids: string[]) => {
        ids.forEach((id) => store.computeScore(id));
        return Promise.resolve();
      },
    };
